### ISSUE TITLE
5.3.0 fails to build on Windows 8.1 using Cygwin

### ISSUE THREAD

**Issue by TrapAlice** [ChaiScript/ChaiScript#121]
gcc version 4.8.2 (GCC)
GNU Make 4.0
cmake version 2.8.11.2

When attempting to build after running cmake and make I get the errors

```
In file included from /home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/chaiscript.hpp:759:0,
                 from /home/Alicia/ChaiScript-Release-5.3.0/unittests/arithmetic_conversions_test.cpp:3:
/home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/language/chaiscript_engine.hpp: In constructor ‘chaiscript::ChaiScript::ChaiScript(const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&)’:
/home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/language/chaiscript_engine.hpp:432:7: error: ‘Dl_info’ was not declared in this scope
       Dl_info rInfo;
       ^
/home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/language/chaiscript_engine.hpp:432:15: error: expected ‘;’ before ‘rInfo’
       Dl_info rInfo;
               ^
/home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/language/chaiscript_engine.hpp:433:16: error: ‘rInfo’ was not declared in this scope
       memset( &rInfo, 0, sizeof(rInfo) );
                ^
/home/Alicia/ChaiScript-Release-5.3.0/include/chaiscript/language/chaiscript_engine.hpp:436:45: error: ‘dladdr’ was not declared in this scope
       if ( dladdr((void*)(u.out_ptr), &rInfo) && rInfo.dli_fname ) {
                                             ^
```
