### ISSUE TITLE
compilation errors with MSVC2013

### ISSUE THREAD

**Issue by alphasilver** [ChaiScript/ChaiScript#148]
Hi,
I'm trying to use ChaiScript for the first time, and I'm having some trouble.

I'm using Visual Studio 2013 update 2 to compile the following simple Win32 application:

``` C++
#include "stdafx.h"
#include <chaiscript/chaiscript.hpp>

double function(int i, double j)
{
    return i * j;
}
int _tmain(int argc, _TCHAR* argv[])
{
    chaiscript::ChaiScript chai;
    chai.add(&function, "function");
    double d = chai.eval<double>("function(3, 4.75);");

    return 0;
}
```

I have tried to compile with the MSVC and the Intel 15.0 compilers but I always get errors:
1) MSVC
1>------ Build started: Project: ChaiScript01, Configuration: Debug Win32 ------
1>  ChaiScript01.cpp
1>c:\sdk\chaiscript 5.5.0\win32\include\chaiscript\language\chaiscript_engine.hpp(676): error C2664: 'void chaiscript::detail::Dispatch_Engine::add(const chaiscript::Type_Info &,const std::string &)' : cannot convert argument 1 from 'double (__cdecl *const )(int,double)' to 'const chaiscript::Proxy_Function &'
1>          Reason: cannot convert from 'double (__cdecl *const )(int,double)' to 'const chaiscript::Proxy_Function'
1>          Constructor for class 'std::shared_ptrchaiscript::dispatch::Proxy_Function_Base' is declared 'explicit'
1>          c:\projects_vs2013\chaiscript01\chaiscript01\chaiscript01.cpp(21) : see reference to function template instantiation 'chaiscript::ChaiScript &chaiscript::ChaiScript::add<double(__cdecl *)(int,double)>(const T &,const std::string &)' being compiled
1>          with
1>          [
1>              T=double (__cdecl *)(int,double)
1>          ]

2) Intel 15.0
1>------ Build started: Project: ChaiScript01, Configuration: Debug Win32 ------
1>  ChaiScript01.cpp
1>C:\SDK\chaiscript 5.5.0\win32\include\chaiscript/language/chaiscript_engine.hpp(676): error : no instance of overloaded function "chaiscript::detail::Dispatch_Engine::add" matches the argument list
1>              argument types are: (double (_const)(int, double), const std::string)
1>              object type is: chaiscript::detail::Dispatch_Engine
1>          m_engine.add(t_t, t_name);
1>                   ^
1>            detected during instantiation of "chaiscript::ChaiScript &chaiscript::ChaiScript::add(const T &, const std::string &) [with T=double (_)(int, double)]" at line 21 of "ChaiScript01.cpp"
1> 
1>  compilation aborted for ChaiScript01.cpp (code 2)

Can you help me with this? Am I missing something?

In chaiscript.com I read that ChaiScript was fully tested with MSVC2013. Is the visual studio project file to build the library available anywhere?

Thank you. Regards.
