### ISSUE TITLE
Error while adding lambda functions in version 5.7.1

### ISSUE THREAD

**Issue by nxtruong** [ChaiScript/ChaiScript#199]
The following used to work in version 5.7.0:
```c++
chai.add(fun<void (int)>([&ws](int t) { ws.settings.ack_timeout = t; }), "ack_timeout");
```
However, when I upgraded to version 5.7.1, it caused compilation error:
```
/Users/truong/work/working/obn/smnchai/src/smnchai_api.cpp:126:14: error: no
      matching function for call to 'fun'
    chai.add(fun<void (int)>([&ws](int t) { ws.settings.ack_timeout = t...
             ^~~~~~~~~~~~~~~
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:39:20: note: 
      candidate function [with T = void (int)] not viable: no known conversion
      from '(lambda at
      /Users/truong/work/working/obn/smnchai/src/smnchai_api.cpp:126:30)' to
      'void (&)(int)' for 1st argument
    Proxy_Function fun(const T &t)
                   ^
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:48:20: note: 
      candidate template ignored: substitution failure [with Ret = void (int)]:
      function cannot return function type 'void (int)'
    Proxy_Function fun(Ret (*func)(Param...))
                   ^   ~~~
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:58:20: note: 
      candidate template ignored: substitution failure [with Ret = void (int)]:
      function cannot return function type 'void (int)'
    Proxy_Function fun(Ret (Class::*t_func)(Param...) const)
                   ^   ~~~
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:67:20: note: 
      candidate template ignored: substitution failure [with Ret = void (int)]:
      function cannot return function type 'void (int)'
    Proxy_Function fun(Ret (Class::*t_func)(Param...))
                   ^   ~~~
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:78:20: note: 
      candidate template ignored: could not match 'void (Class::*)(int)' against
      '(lambda at
      /Users/truong/work/working/obn/smnchai/src/smnchai_api.cpp:126:30)'
    Proxy_Function fun(T Class::* m /*, typename std::enable_if<std::is_...
                   ^
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:105:20: note: 
      candidate function template not viable: requires 2 arguments, but 1 was
      provided
    Proxy_Function fun(T &&t, const Q &q)
                   ^
/Users/truong/work/working/obn/smnchai/include/chaiscript/dispatchkit/register_function.hpp:131:20: note: 
      candidate function template not viable: requires 3 arguments, but 1 was
      provided
    Proxy_Function fun(T &&t, Q &&q, R &&r)
                   ^
```

My system is Mac OS with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0.

**Comment by nxtruong** [comment]
By removing the lambda type signature, the error was resolved. So it's good now, although it's incompatible with 5.7.0. I had to go through my code to remove all the lambda type signatures in the template `fun<...>` to make my code compile.

**Comment by lefticus** [comment]
I changed function type resolution between 5.7.0 and 5.7.1 as you noticed. I was afraid I might break some existing code, and was very tempted to make it a 6.0 release just in case - but wasn't sure. I also knew that there was a simple work around (as you saw) for any cases it did break.

Sorry for the confusion.
