### ISSUE TITLE
Compiler error with MSVC2017 - 15.6.1

### ISSUE THREAD

**Issue by acki-m** [ChaiScript/ChaiScript#425]
* Compiler Used:
MSVC 15.6.1 C++17
compiled with c++17 flag
 * Operating System:
win10
 * Architecture (ARM/x86/32bit/64bit/etc): 
 x64

### Expected Behavior 
No compile error
### Actual Behavior 
```
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C2825: 'T': must be a class or namespace when followed by '::'
1>e:\software\rttr_project\rttr-master\3rd_party\chaiscript-6.0.0\chaiscript\dispatchkit\register_function.hpp(45): note: see reference to class template instantiation 'chaiscript::dispatch::detail::Callable_Traits<T>' being compiled
1>        with
1>        [
1>            T=bool (__cdecl *)(const chaiscript::Boxed_Value &,const chaiscript::Boxed_Value &) noexcept
1>        ]
1>e:\software\rttr_project\rttr-master\3rd_party\chaiscript-6.0.0\chaiscript\dispatchkit\bootstrap.hpp(522): note: see reference to function template instantiation 'chaiscript::Proxy_Function chaiscript::fun<bool(__cdecl *)(const chaiscript::Boxed_Value &,const chaiscript::Boxed_Value &) noexcept>(const T &)' being compiled
1>        with
1>        [
1>            T=bool (__cdecl *)(const chaiscript::Boxed_Value &,const chaiscript::Boxed_Value &) noexcept
1>        ]
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C2510: 'T': left of '::' must be a class/struct/union
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C2065: '()': undeclared identifier
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C2955: 'chaiscript::dispatch::detail::Function_Signature': use of class template requires template argument list
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(78): note: see declaration of 'chaiscript::dispatch::detail::Function_Signature'
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C2039: 'Signature': is not a member of 'chaiscript::dispatch::detail::Function_Signature<T>'
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C3646: 'Signature': unknown override specifier
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(99): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C2825: 'T': must be a class or namespace when followed by '::'
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C2510: 'T': left of '::' must be a class/struct/union
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C2065: '()': undeclared identifier
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C2955: 'chaiscript::dispatch::detail::Function_Signature': use of class template requires template argument list
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(78): note: see declaration of 'chaiscript::dispatch::detail::Function_Signature'
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C2039: 'Return_Type': is not a member of 'chaiscript::dispatch::detail::Function_Signature<T>'
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C3646: 'Return_Type': unknown override specifier
1> chaiscript-6.0.0\chaiscript\dispatchkit\callable_traits.hpp(100): error C4430: missing type specifier - int assumed. Note: C++ do
```
### Minimal Example to Reproduce Behavior
Compile with 6.0.0

I used chai script 6.0.0

PS: additional issue:
I cannot use:
`chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());` in version 6:
```
 error C2664: 'chaiscript::ChaiScript::ChaiScript(const chaiscript::ChaiScript &)': cannot convert argument 1 from 'chaiscript::ModulePtr' to 'std::vector<std::string,std::allocator<_Ty>>'
```
Is this on purpose?

**Comment by lefticus** [comment]
Fixed on `develop` already.

**Comment by acki-m** [comment]
@lefticus 
What about the error with: `chaiscript::ChaiScript chai(chaiscript::Std_Lib::library());`
is this not available anymore in the newest version?

**Comment by lefticus** [comment]
The default now is to compile in the stdlib, it was causing far too much user confusion with the old version. Now if you want do compile it separately you need to use `ChaiScript_Basic`
