### ISSUE TITLE
Can't compile with MSVC 14.20.27508

### ISSUE THREAD

**Issue by jeevcat** [ChaiScript/ChaiScript#488]
* Compiler Used: MSVC 14.20.27508 (Visual Studio 2019 16.0.4)
 * Operating System: Windows 10 Build 18895
 * Architecture:  x64
 

### Expected Behavior 
No compile error

### Actual Behavior 
<details>
  <summary>Develop branch</summary>

```
chaiscript\dispatchkit\proxy_functions.hpp(80): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(80): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(120): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(120): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(255): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(255): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(256): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(256): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(257): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(257): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit/dispatchkit.hpp(1306): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit/dispatchkit.hpp(1306): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit/dispatchkit.hpp(1307): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit/dispatchkit.hpp(1307): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(80): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(80): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(120): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(120): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(255): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(255): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(256): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(256): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit\proxy_functions.hpp(257): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit\proxy_functions.hpp(257): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit/dispatchkit.hpp(1306): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit/dispatchkit.hpp(1306): note: a non-constant (sub-)expression was encountered
chaiscript\dispatchkit/dispatchkit.hpp(1307): error C2131: expression did not evaluate to a constant
chaiscript\dispatchkit/dispatchkit.hpp(1307): note: a non-constant (sub-)expression was encountered
```

</details>

### Minimal Example to Reproduce Behavior
First I failed to build using latest release (6.1.0) with same error as #425.

Then I tried latest develop branch with c++17 flag, which resulted in the compile error log above. This seems to be the same issue as #460. 

I also tried the VS_2019_fixes branch but then had some different compile errors:

<details>
  <summary>VS_2019_fixes branch</summary>

```
MSVC\14.20.27508\INCLUDE\variant(500): error C4582: 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Tail': constructor is not implicitly called
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(500): note: while compiling class template member function 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Variant_storage_(void) noexcept'
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(872): note: see reference to function template instantiation 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Variant_storage_(void) noexcept' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(852): note: see reference to class template instantiation 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(954): note: see reference to class template instantiation 'std::_Variant_base<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(22): note: see reference to class template instantiation 'std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(43): note: see reference to class template instantiation 'std::_Non_trivial_copy<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(65): note: see reference to class template instantiation 'std::_Non_trivial_move<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(105): note: see reference to class template instantiation 'std::_Non_trivial_copy_assign<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(1015): note: see reference to class template instantiation 'std::_Non_trivial_move_assign<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  chaiscript\utility\json.hpp(140): note: see reference to class template instantiation 'std::variant<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  chaiscript\dispatchkit/dispatchkit.hpp(438): note: see reference to class template instantiation 'chaiscript::utility::QuickFlatMap<std::string,std::shared_ptr<std::vector<chaiscript::Proxy_Function,std::allocator<_Ty>>>,chaiscript::str_equal>' being compiled
          with
          [
              _Ty=chaiscript::Proxy_Function
          ]
chaiscript\dispatchkit\proxy_functions.hpp(987): error C2664: 'chaiscript::Boxed_Value chaiscript::dispatch::detail::dispatch_with_conversions<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,Funcs>(InItr,const InItr &,const chaiscript::dispatch::detail::Function_Params &,const chaiscript::Type_Conversions_State &,const Funcs &)': cannot convert argument 3 from 'const chaiscript::Function_Params' to 'const chaiscript::dispatch::detail::Function_Params &'
          with
          [
              _Ty=std::pair<size_t,const chaiscript::dispatch::Proxy_Function_Base *>,
              Funcs=std::vector<chaiscript::Proxy_Function,std::allocator<chaiscript::Proxy_Function>>,
              InItr=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<std::pair<size_t,const chaiscript::dispatch::Proxy_Function_Base *>>>>
          ]
  chaiscript\dispatchkit\proxy_functions.hpp(987): note: Reason: cannot convert from 'const chaiscript::Function_Params' to 'const chaiscript::dispatch::detail::Function_Params'
  chaiscript\dispatchkit\proxy_functions.hpp(987): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  chaiscript\dispatchkit/dispatchkit.hpp(326): note: see reference to function template instantiation 'chaiscript::Boxed_Value chaiscript::dispatch::dispatch<std::vector<chaiscript::Proxy_Function,std::allocator<_Ty>>>(const Funcs &,const chaiscript::Function_Params &,const chaiscript::Type_Conversions_State &)' being compiled
          with
          [
              _Ty=chaiscript::Proxy_Function,
              Funcs=std::vector<chaiscript::Proxy_Function,std::allocator<chaiscript::Proxy_Function>>
          ]
chaiscript\dispatchkit\function_signature.hpp(139): error C2641: cannot deduce template arguments for 'chaiscript::dispatch::detail::Function_Signature'
  chaiscript\language\../dispatchkit/register_function.hpp(91): note: see reference to function template instantiation 'auto chaiscript::dispatch::detail::function_signature<T>(const Func &)' being compiled
          with
          [
              T=const FScriptFunctionOneFloat *,
              Func=const FScriptFunctionOneFloat *
          ]
  D:\Sam\Documents\Unreal Projects\Hal\Source\ChaiScript\Private\ScriptController.cpp(7): note: see reference to function template instantiation 'chaiscript::Proxy_Function chaiscript::fun<const FScriptFunctionOneFloat*>(T &&)' being compiled
          with
          [
              T=const FScriptFunctionOneFloat *
          ]
  MSVC\14.20.27508\INCLUDE\type_traits(868): note: see reference to class template instantiation 'chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>' being compiled
  MSVC\14.20.27508\INCLUDE\variant(969): note: see reference to class template instantiation 'std::is_trivially_destructible<chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>>' being compiled
  MSVC\14.20.27508\INCLUDE\variant(969): note: see reference to variable template 'const bool conjunction_v<std::is_trivially_destructible<std::nullptr_t>,std::is_trivially_destructible<chaiscript::utility::QuickFlatMap<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,json::JSON,std::equal_to<void> > >,std::is_trivially_destructible<std::vector<json::JSON,std::allocator<json::JSON> > >,std::is_trivially_destructible<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::is_trivially_destructible<double>,std::is_trivially_destructible<__int64>,std::is_trivially_destructible<bool> >' being compiled
  MSVC\14.20.27508\INCLUDE\variant(1015): note: see reference to alias template instantiation 'std::_Variant_destroy_layer<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
chaiscript\dispatchkit\function_signature.hpp(139): error C2783: 'chaiscript::dispatch::detail::Function_Signature<Ret,Params,IsNoExcept,IsMember,IsMemberObject,IsObject> chaiscript::dispatch::detail::Function_Signature(T &&) noexcept': could not deduce template argument for 'Ret'
  chaiscript\dispatchkit\function_signature.hpp(22): note: see declaration of 'chaiscript::dispatch::detail::Function_Signature'
chaiscript\dispatchkit\function_signature.hpp(139): error C2783: 'chaiscript::dispatch::detail::Function_Signature<Ret,Params,IsNoExcept,IsMember,IsMemberObject,IsObject> chaiscript::dispatch::detail::Function_Signature(T &&) noexcept': could not deduce template argument for 'Params'
  chaiscript\dispatchkit\function_signature.hpp(22): note: see declaration of 'chaiscript::dispatch::detail::Function_Signature'
chaiscript\dispatchkit\function_signature.hpp(139): error C2780: 'chaiscript::dispatch::detail::Function_Signature<Ret,Params,IsNoExcept,IsMember,IsMemberObject,IsObject> chaiscript::dispatch::detail::Function_Signature(void) noexcept': expects 0 arguments - 1 provided
  chaiscript\dispatchkit\function_signature.hpp(23): note: see declaration of 'chaiscript::dispatch::detail::Function_Signature'
chaiscript\dispatchkit\function_signature.hpp(139): error C2440: 'initializing': cannot convert from 'initializer list' to 'chaiscript::dispatch::detail::Function_Signature'
  chaiscript\dispatchkit\function_signature.hpp(139): note: No constructor could take the source type, or constructor overload resolution was ambiguous
chaiscript\language\../dispatchkit/register_function.hpp(91): error C2672: 'chaiscript::dispatch::detail::make_callable': no matching overloaded function found
chaiscript\language\../dispatchkit/register_function.hpp(91): error C2784: 'auto chaiscript::dispatch::detail::make_callable(Func &&,chaiscript::dispatch::detail::Function_Signature<Ret,chaiscript::dispatch::detail::Function_Params<Param...>,Is_Noexcept,Is_Member,Is_MemberObject,false>)': could not deduce template argument for 'chaiscript::dispatch::detail::Function_Signature<Ret,chaiscript::dispatch::detail::Function_Params<Param...>,Is_Noexcept,Is_Member,Is_MemberObject,false>' from 'void'
  chaiscript\language\../dispatchkit/register_function.hpp(62): note: see declaration of 'chaiscript::dispatch::detail::make_callable'
chaiscript\language\../dispatchkit/register_function.hpp(91): error C2784: 'auto chaiscript::dispatch::detail::make_callable(Func &&,chaiscript::dispatch::detail::Function_Signature<Ret,chaiscript::dispatch::detail::Function_Params<Object,Param...>,Is_Noexcept,false,false,true>)': could not deduce template argument for 'chaiscript::dispatch::detail::Function_Signature<Ret,chaiscript::dispatch::detail::Function_Params<Object,Param...>,Is_Noexcept,false,false,true>' from 'void'
  chaiscript\language\../dispatchkit/register_function.hpp(56): note: see declaration of 'chaiscript::dispatch::detail::make_callable'
  [2/5] ScriptController.gen.cpp
MSVC\14.20.27508\INCLUDE\variant(500): error C4582: 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Tail': constructor is not implicitly called
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(500): note: while compiling class template member function 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Variant_storage_(void) noexcept'
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(872): note: see reference to function template instantiation 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>::_Variant_storage_(void) noexcept' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(852): note: see reference to class template instantiation 'std::_Variant_storage_<false,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(954): note: see reference to class template instantiation 'std::_Variant_base<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(22): note: see reference to class template instantiation 'std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(43): note: see reference to class template instantiation 'std::_Non_trivial_copy<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(65): note: see reference to class template instantiation 'std::_Non_trivial_move<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\xsmf_control.h(105): note: see reference to class template instantiation 'std::_Non_trivial_copy_assign<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  MSVC\14.20.27508\INCLUDE\variant(1015): note: see reference to class template instantiation 'std::_Non_trivial_move_assign<std::_Variant_destroy_layer_<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>,std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<_Ty,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  chaiscript\utility\json.hpp(140): note: see reference to class template instantiation 'std::variant<std::nullptr_t,chaiscript::utility::QuickFlatMap<std::string,json::JSON,std::equal_to<void>>,std::vector<json::JSON,std::allocator<_Ty>>,std::string,double,int64_t,bool>' being compiled
          with
          [
              _Ty=json::JSON
          ]
  chaiscript\dispatchkit/dispatchkit.hpp(438): note: see reference to class template instantiation 'chaiscript::utility::QuickFlatMap<std::string,std::shared_ptr<std::vector<chaiscript::Proxy_Function,std::allocator<_Ty>>>,chaiscript::str_equal>' being compiled
          with
          [
              _Ty=chaiscript::Proxy_Function
          ]
chaiscript\dispatchkit\proxy_functions.hpp(987): error C2664: 'chaiscript::Boxed_Value chaiscript::dispatch::detail::dispatch_with_conversions<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,Funcs>(InItr,const InItr &,const chaiscript::dispatch::detail::Function_Params &,const chaiscript::Type_Conversions_State &,const Funcs &)': cannot convert argument 3 from 'const chaiscript::Function_Params' to 'const chaiscript::dispatch::detail::Function_Params &'
          with
          [
              _Ty=std::pair<size_t,const chaiscript::dispatch::Proxy_Function_Base *>,
              Funcs=std::vector<chaiscript::Proxy_Function,std::allocator<chaiscript::Proxy_Function>>,
              InItr=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<std::pair<size_t,const chaiscript::dispatch::Proxy_Function_Base *>>>>
          ]
  chaiscript\dispatchkit\proxy_functions.hpp(987): note: Reason: cannot convert from 'const chaiscript::Function_Params' to 'const chaiscript::dispatch::detail::Function_Params'
  chaiscript\dispatchkit\proxy_functions.hpp(987): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  chaiscript\dispatchkit/dispatchkit.hpp(326): note: see reference to function template instantiation 'chaiscript::Boxed_Value chaiscript::dispatch::dispatch<std::vector<chaiscript::Proxy_Function,std::allocator<_Ty>>>(const Funcs &,const chaiscript::Function_Params &,const chaiscript::Type_Conversions_State &)' being compiled
          with
          [
              _Ty=chaiscript::Proxy_Function,
              Funcs=std::vector<chaiscript::Proxy_Function,std::allocator<chaiscript::Proxy_Function>>
          ]
```
</details>

Sorry for the wall of compile logs - just wanted to include all information.

**Comment by tan-wei** [comment]
I meet the same problem.
